-- =============================================================
-- ARTEFATO: TELA 1 - MATERIALIZED VIEW
-- OBJETIVO: Listar atividades com vagas disponíveis e datas futuras.
-- VÍNCULO: R1 (Gestão de atividades)
-- =============================================================

CREATE MATERIALIZED VIEW VM_VAGAS_ABERTAS AS
SELECT 
    ID_ATIVIDADE,
    DS_TITULO,
    DT_ATIVIDADE,
    QT_VAGAS
FROM TB_ATIVIDADE
WHERE QT_VAGAS > 0 
  AND DT_ATIVIDADE >= CURRENT_DATE;

-- =============================================================
-- STORED PROCEDURE: REALIZAR INSCRIÇÃO
-- =============================================================

CREATE OR REPLACE PROCEDURE SP_REALIZAR_INSCRICAO(
    p_id_participante INTEGER,
    p_id_atividade    INTEGER,
    p_nm_usuario_app  VARCHAR
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_vagas_atuais INTEGER;
    v_dt_atividade DATE;
BEGIN
    SELECT QT_VAGAS, DT_ATIVIDADE
    INTO v_vagas_atuais, v_dt_atividade
    FROM TB_ATIVIDADE
    WHERE ID_ATIVIDADE = p_id_atividade;

    IF v_dt_atividade IS NULL THEN 
        RAISE EXCEPTION 'Atividade não encontrada.';
    END IF;

    IF v_dt_atividade < CURRENT_DATE THEN
        RAISE EXCEPTION 'Atividade já expirada.';
    END IF;

    IF v_vagas_atuais <= 0 THEN
        RAISE EXCEPTION 'Não há vagas disponíveis.';
    END IF;

    UPDATE TB_ATIVIDADE
    SET QT_VAGAS = QT_VAGAS - 1
    WHERE ID_ATIVIDADE = p_id_atividade;

    UPDATE TB_PARTICIPANTE
    SET DS_EMAIL = DS_EMAIL
    WHERE ID_PARTICIPANTE = p_id_participante;

    INSERT INTO TB_INSCRICAO (ID_PARTICIPANTE, ID_ATIVIDADE, DT_INSCRICAO, ST_CONFIRMADA)
    VALUES (p_id_participante, p_id_atividade, CURRENT_TIMESTAMP, FALSE);

    INSERT INTO TA_AUDITORIA (NM_TABELA, TP_OPERACAO, ID_REGISTRO, NM_USUARIO_APLICACAO, DS_VALOR_NOVO)
    VALUES ('TB_INSCRICAO', 'I', p_id_participante || '-' || p_id_atividade, p_nm_usuario_app, 'Sucesso');

    RAISE NOTICE '✓ Inscrição realizada com sucesso!';
END;
$$;

-- =============================================================
-- ARTEFATO: TELA 2 - GESTÃO DE PRESENÇA E CERTIFICADOS
-- =============================================================

CREATE MATERIALIZED VIEW VM_PENDENCIAS_CERTIFICACAO AS
SELECT 
    P.ID_PARTICIPANTE,
    P.NM_PARTICIPANTE,
    A.ID_ATIVIDADE,
    A.DS_TITULO
FROM TB_PARTICIPANTE P
JOIN TB_INSCRICAO I ON P.ID_PARTICIPANTE = I.ID_PARTICIPANTE
JOIN TB_ATIVIDADE A ON I.ID_ATIVIDADE = A.ID_ATIVIDADE
LEFT JOIN TB_FEEDBACK F 
       ON P.ID_PARTICIPANTE = F.ID_PARTICIPANTE 
      AND A.ID_ATIVIDADE = F.ID_ATIVIDADE
WHERE I.ST_CONFIRMADA = TRUE 
  AND F.ID_FEEDBACK IS NULL;

CREATE OR REPLACE PROCEDURE SP_GESTAO_PRESENCA_CERTIFICADO(
    p_id_participante INTEGER,
    p_id_atividade    INTEGER,
    p_acao            VARCHAR
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_feedback_existe  INTEGER;
    v_inscricao_existe BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1 
        FROM TB_INSCRICAO 
        WHERE ID_PARTICIPANTE = p_id_participante
          AND ID_ATIVIDADE = p_id_atividade
    )
    INTO v_inscricao_existe;

    IF NOT v_inscricao_existe THEN
        RAISE EXCEPTION 'Inscrição não encontrada.';
    END IF;

    IF p_acao = 'CANCELAR' THEN
        DELETE FROM TB_INSCRICAO
        WHERE ID_PARTICIPANTE = p_id_participante
          AND ID_ATIVIDADE = p_id_atividade;
        RETURN;
    END IF;

    IF p_acao = 'CONFIRMAR' THEN
        SELECT COUNT(*)
        INTO v_feedback_existe
        FROM TB_FEEDBACK
        WHERE ID_PARTICIPANTE = p_id_participante
          AND ID_ATIVIDADE = p_id_atividade;

        IF v_feedback_existe = 0 THEN
            RAISE EXCEPTION 'Feedback obrigatório ausente.';
        END IF;

        UPDATE TB_INSCRICAO
        SET ST_CONFIRMADA = TRUE
        WHERE ID_PARTICIPANTE = p_id_participante
          AND ID_ATIVIDADE = p_id_atividade;

        UPDATE TB_PARTICIPANTE
        SET DS_EMAIL = DS_EMAIL
        WHERE ID_PARTICIPANTE = p_id_participante;

        INSERT INTO TB_CERTIFICADO (
            ID_PARTICIPANTE,
            ID_ATIVIDADE,
            DT_EMISSAO,
            CD_VALIDACAO
        )
        VALUES (
            p_id_participante,
            p_id_atividade,
            CURRENT_DATE,
            'VAL-' || p_id_participante || '-' || p_id_atividade
        );
    END IF;
END;
$$;

-- =============================================================
-- DASHBOARD 1 - ANALÍTICO DE OCUPAÇÃO
-- =============================================================

CREATE MATERIALIZED VIEW VM_DASH_OCUPACAO AS
SELECT 
    E.DS_TITULO AS EVENTO,
    A.DS_TITULO AS ATIVIDADE,
    A.QT_VAGAS,
    COUNT(I.ID_PARTICIPANTE) FILTER (WHERE I.ST_CONFIRMADA = TRUE) AS INSCRITOS_CONFIRMADOS,
    COUNT(I.ID_PARTICIPANTE) AS DEMANDA_TOTAL,
    RANK() OVER (PARTITION BY E.ID_EVENTO ORDER BY COUNT(I.ID_PARTICIPANTE) DESC) AS RANK_POPULARIDADE
FROM TB_EVENTO E
JOIN TB_ATIVIDADE A ON E.ID_EVENTO = A.ID_EVENTO
LEFT JOIN TB_INSCRICAO I ON A.ID_ATIVIDADE = I.ID_ATIVIDADE
GROUP BY E.ID_EVENTO, E.DS_TITULO, A.ID_ATIVIDADE, A.DS_TITULO, A.QT_VAGAS;

CREATE MATERIALIZED VIEW VM_DASH_ADESAO AS
SELECT 
    E.DS_TITULO AS EVENTO,
    I.DT_INSCRICAO,
    COUNT(I.ID_INSCRICAO) AS QTD_DIA,
    SUM(COUNT(I.ID_INSCRICAO)) 
        OVER (PARTITION BY E.ID_EVENTO ORDER BY I.DT_INSCRICAO) AS TOTAL_ACUMULADO
FROM TB_INSCRICAO I
JOIN TB_ATIVIDADE A ON I.ID_ATIVIDADE = A.ID_ATIVIDADE
JOIN TB_EVENTO E ON A.ID_EVENTO = E.ID_EVENTO
GROUP BY E.ID_EVENTO, E.DS_TITULO, I.DT_INSCRICAO;

CREATE MATERIALIZED VIEW VM_DASH_CONVERSAO_FEEDBACK AS
SELECT 
    A.DS_TITULO,
    COUNT(I.ID_PARTICIPANTE) AS TOTAL_INSCRITOS,
    (SELECT COUNT(*) FROM TB_FEEDBACK F WHERE F.ID_ATIVIDADE = A.ID_ATIVIDADE) AS TOTAL_FEEDBACKS,
    ROUND(
        ((SELECT COUNT(*)::NUMERIC FROM TB_FEEDBACK F WHERE F.ID_ATIVIDADE = A.ID_ATIVIDADE) /
         NULLIF(COUNT(I.ID_PARTICIPANTE), 0)) * 100, 2
    ) AS PERC_RETORNO
FROM TB_ATIVIDADE A
JOIN TB_INSCRICAO I ON A.ID_ATIVIDADE = I.ID_ATIVIDADE
GROUP BY A.ID_ATIVIDADE, A.DS_TITULO;

CREATE MATERIALIZED VIEW VM_DASH_CERTIFICACAO_EVENTO AS
SELECT 
    E.DS_TITULO AS EVENTO,
    COUNT(C.ID_CERTIFICADO) AS TOTAL_EMITIDOS,
    SUM(A.QT_CARGA_HORARIA) AS CH_TOTAL_OFERECIDA
FROM TB_EVENTO E
JOIN TB_ATIVIDADE A ON E.ID_EVENTO = A.ID_EVENTO
LEFT JOIN TB_CERTIFICADO C ON A.ID_ATIVIDADE = C.ID_ATIVIDADE
GROUP BY E.ID_EVENTO, E.DS_TITULO;

CREATE OR REPLACE PROCEDURE SP_MANUTENCAO_DASHBOARD_1()
LANGUAGE plpgsql
AS $$
BEGIN
    REFRESH MATERIALIZED VIEW VM_DASH_OCUPACAO;
    REFRESH MATERIALized VIEW VM_DASH_ADESAO;
    REFRESH MATERIALIZED VIEW VM_DASH_CONVERSAO_FEEDBACK;
    REFRESH MATERIALIZED VIEW VM_DASH_CERTIFICACAO_EVENTO;
    RAISE NOTICE '✓ Dashboard 1 sincronizado com sucesso.';
END;
$$;

-- =============================================================
-- DASHBOARD 2 - PERFIL DO PÚBLICO E QUALIDADE
-- =============================================================

CREATE MATERIALIZED VIEW VM_DASH_DOMINIOS_EMAIL AS
SELECT 
    DOMINIO,
    TOTAL_INSCRICOES,
    RANK() OVER (ORDER BY TOTAL_INSCRICOES DESC) AS RANK_DOMINIO
FROM (
    SELECT 
        SUBSTRING(P.DS_EMAIL FROM POSITION('@' IN P.DS_EMAIL) + 1) AS DOMINIO,
        COUNT(I.ID_INSCRICAO) AS TOTAL_INSCRICOES
    FROM TB_PARTICIPANTE P
    JOIN TB_INSCRICAO I ON P.ID_PARTICIPANTE = I.ID_PARTICIPANTE
    GROUP BY DOMINIO
) sub
LIMIT 5;

CREATE MATERIALIZED VIEW VM_DASH_QUALIDADE_MODALIDADE AS
SELECT 
    A.TP_FORMATO,
    COUNT(F.ID_FEEDBACK) AS QTD_AVALIACOES,
    ROUND(AVG(F.VL_NOTA_CONTEUDO), 2) AS MEDIA_CONTEUDO,
    (SELECT ROUND(AVG(VL_NOTA_CONTEUDO), 2) FROM TB_FEEDBACK) AS MEDIA_GLOBAL_EVENTO
FROM TB_ATIVIDADE A
JOIN TB_FEEDBACK F ON A.ID_ATIVIDADE = F.ID_ATIVIDADE
GROUP BY A.TP_FORMATO;

CREATE MATERIALIZED VIEW VM_DASH_PARTICIPACAO_EVENTO AS
SELECT 
    E.DS_TITULO AS EVENTO,
    COUNT(I.ID_INSCRICAO) AS TOTAL_PARTICIPANTES
FROM TB_EVENTO E
JOIN TB_ATIVIDADE A ON E.ID_EVENTO = A.ID_EVENTO
JOIN TB_INSCRICAO I ON A.ID_ATIVIDADE = I.ID_ATIVIDADE
GROUP BY E.ID_EVENTO, E.DS_TITULO;

CREATE MATERIALIZED VIEW VM_DASH_IDADE_PARTICIPANTE AS
SELECT 
    E.DS_TITULO AS EVENTO,
    ROUND(AVG(EXTRACT(YEAR FROM AGE(P.DT_NASCIMENTO))), 0) AS IDADE_MEDIA
FROM TB_EVENTO E
JOIN TB_ATIVIDADE A ON E.ID_EVENTO = A.ID_EVENTO
JOIN TB_INSCRICAO I ON A.ID_ATIVIDADE = I.ID_ATIVIDADE
JOIN TB_PARTICIPANTE P ON I.ID_PARTICIPANTE = P.ID_PARTICIPANTE
GROUP BY E.ID_EVENTO, E.DS_TITULO;

CREATE MATERIALIZED VIEW VM_DASH_EFICIENCIA_CERTIFICADO AS
SELECT 
    A.DS_TITULO AS ATIVIDADE,
    COUNT(I.ID_INSCRICAO) AS INSCRITOS,
    COUNT(C.ID_CERTIFICADO) AS CERTIFICADOS_EMITIDOS
FROM TB_ATIVIDADE A
JOIN TB_INSCRICAO I ON A.ID_ATIVIDADE = I.ID_ATIVIDADE
LEFT JOIN TB_CERTIFICADO C 
       ON I.ID_PARTICIPANTE = C.ID_PARTICIPANTE
      AND I.ID_ATIVIDADE = C.ID_ATIVIDADE
GROUP BY A.ID_ATIVIDADE, A.DS_TITULO;

CREATE MATERIALIZED VIEW VM_DASH_OCUPACAO_FISICA AS
SELECT 
    E.DS_TITULO AS EVENTO,
    A.DS_TITULO AS ATIVIDADE,
    A.TP_MODALIDADE,
    COUNT(I.ID_INSCRICAO) AS OCUPACAO_REAL
FROM TB_EVENTO E
JOIN TB_ATIVIDADE A ON E.ID_EVENTO = A.ID_EVENTO
JOIN TB_INSCRICAO I ON A.ID_ATIVIDADE = I.ID_ATIVIDADE
WHERE A.TP_FORMATO = 'Presencial'
GROUP BY E.DS_TITULO, A.DS_TITULO, A.TP_MODALIDADE;

CREATE OR REPLACE PROCEDURE SP_MANUTENCAO_DASHBOARD_2()
LANGUAGE plpgsql
AS $$
BEGIN
    REFRESH MATERIALIZED VIEW VM_DASH_DOMINIOS_EMAIL;
    REFRESH MATERIALIZED VIEW VM_DASH_QUALIDADE_MODALIDADE;
    REFRESH MATERIALIZED VIEW VM_DASH_PARTICIPACAO_EVENTO;
    REFRESH MATERIALIZED VIEW VM_DASH_IDADE_PARTICIPANTE;
    REFRESH MATERIALIZED VIEW VM_DASH_EFICIENCIA_CERTIFICADO;
    REFRESH MATERIALIZED VIEW VM_DASH_OCUPACAO_FISICA;
    RAISE NOTICE 'Dashboard 2 (Operacional) atualizado com sucesso.';
END;
$$;
